eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka:8761/eureka
  instance:
    preferIpAddress: true
    hostname: eureka-0
